workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    working_directory: frontend

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.petits.quizz.de.geo

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true

      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build IPA
        script: |
          BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
          flutter build ipa --release --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - vladislav.razyvika@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

  ios-production:
    name: iOS Production
    max_build_duration: 90
    instance_type: mac_mini_m2
    working_directory: frontend

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.petits.quizz.de.geo

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Run tests
        script: |
          flutter test
        ignore_failure: false

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Build IPA
        script: |
          BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
          flutter build ipa --release --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - vladislav.razyvika@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

#      app_store_connect:
#        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
#        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
#        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
#        submit_to_testflight: true
#        submit_to_app_store: false  # Mettre true pour production

# android prod inc


#        android-production:
#          name: Android Production
#          max_build_duration: 60
#          instance_type: linux_x2
#          working_directory: frontend
#
#          environment:
#            flutter: stable
#            java: 17
#
#            groups:
#              - google_play_credentials
#
#            vars:
#              PACKAGE_NAME: "com.petits.quizz.de.geo"
#
#          triggering:
#            events:
#              - push
#              - tag
#            branch_patterns:
#              - pattern: 'main'
#                include: true
#                source: true
#            tag_patterns:
#              - pattern: 'v*'
#                include: true
#            cancel_previous_builds: true
#
#          scripts:
#            - name: Set up local properties
#              script: |
#                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
#
#            - name: Get Flutter packages
#              script: |
#                flutter packages pub get
#
#            - name: Flutter analyze
#              script: |
#                flutter analyze
#
#            - name: Run tests
#              script: |
#                flutter test
#              ignore_failure: false
#
#            - name: Build APK
#              script: |
#                BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
#                flutter build apk --release --build-number=$BUILD_NUMBER
#
#            - name: Build App Bundle
#              script: |
#                BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
#                flutter build appbundle --release --build-number=$BUILD_NUMBER
#
#          artifacts:
#            - build/app/outputs/**/*.apk
#            - build/app/outputs/**/*.aab
#
#          publishing:
#            email:
#              recipients:
#                - votre-email@example.com
#              notify:
#                success: true
#                failure: true
#
#            google_play:
#              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#              track: internal
#              submit_as_draft: true