workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    working_directory: frontend
    integrations:
      app_store_connect: last_key_intgration_created

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.petits.quizz.de.geo

      vars:
        TEAM_ID: 3UZ57ACSD9
        BUNDLE_ID: com.petits.quizz.de.geo

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Récupérer les fichiers de signature depuis Apple Developer Portal
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY \
            --platform IOS
          
          # Ajouter les certificats au keychain
          keychain add-certificates
          
          # Lister les profiles disponibles pour debug
          echo "=== Profiles disponibles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || true
          
          # Appliquer les profils de provisioning
          xcode-project use-profiles
          
          # Vérifier la configuration Xcode
          echo "=== Configuration Xcode ==="
          cd ios
          xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Runner -configuration Release | grep -E 'DEVELOPMENT_TEAM|PROVISIONING_PROFILE|CODE_SIGN_IDENTITY'



      - name: Get Flutter packages
        script: |
          flutter packages pub get

#      - name: Flutter analyze
#        script: |
#          flutter analyze
#        ignore_failure: true

      - name: Force iOS deployment target to 13.0 (robust version)
        script: |
          cd ios

          # 1. Supprime TOUTES les lignes "platform :ios" (commentées ou pas)
          sed -i '' '/^[[:space:]]*#*[[:space:]]*platform[[:space:]]*:[[:space:]]*ios.*/d' Podfile

          # 2. Ajoute la bonne ligne juste après le commentaire "# Flutter" (ou au début si pas trouvé)
          sed -i '' '/^# Flutter/a\
          platform :ios, '\''13.0'\''
          ' Podfile
          # Si jamais la ligne "# Flutter" n'existe pas, on force au tout début
          if ! grep -q "^platform :ios" Podfile; then
            sed -i '' '1s/^/platform :ios, '\''13.0'\''\n/' Podfile
          fi

          # 3. Supprime un éventuel ancien post_install ajouté par nous (évite les doublons)
          sed -i '' '/^post_install do |installer|$/,/^end$/d' Podfile

          # 4. Ajoute (ou remplace) le post_install à la toute fin du fichier
          cat << 'EOF' >> Podfile

          post_install do |installer|
          installer.pods_project.targets.each do |target|
          flutter_additional_ios_build_settings(target)

          target.build_configurations.each do |config|
          # Force le deployment target à 13.0 pour tous les pods
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

          # Optionnel mais recommandé sur Codemagic (évite des warnings Xcode 16+)
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
          end
          end
          end
          EOF

      - name: Update iOS settings
        script: |
          cd ios
          
          # Forcer le team ID dans le projet
          /usr/libexec/PlistBuddy -c "Set :DEVELOPMENT_TEAM 3UZ57ACSD9" Runner.xcodeproj/project.pbxproj 2>/dev/null || true

#          # Mettre à jour le deployment target
#          grep -rl "IPHONEOS_DEPLOYMENT_TARGET = .*;" . | xargs sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g"


      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

#      - name: Flutter build IPA
#        script: |
#          BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
#
#          flutter build ipa \
#            --release \
#            --build-number=$BUILD_NUMBER

      - name: Build IPA avec configuration explicite
        script: |
          BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
          
          # Créer un export_options.plist temporaire
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>3UZ57ACSD9</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF
          
          # Build avec export options
          flutter build ipa \
            --release \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision
      - ios/Runner.xcarchive

    publishing:
      email:
        recipients:
          - vlad.razyvika@outlook.fr
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false
#
#    ios-production:
#      name: iOS Production
#      max_build_duration: 90
#      instance_type: mac_mini_m2
#      working_directory: frontend
#      integrations:
#        app_store_connect: last_key_intgration_created
#
#      environment:
#        flutter: stable
#        xcode: latest
#        cocoapods: default
#
#        ios_signing:
#          distribution_type: app_store
#          bundle_identifier: com.petits.quizz.de.geo
#
#      triggering:
#        events:
#          - tag
#        tag_patterns:
#          - pattern: 'v*'
#            include: true
#        cancel_previous_builds: true
#
#      scripts:
#        - name: Set up code signing
#          script: |
#            keychain initialize
#            keychain add-certificates
#            xcode-project use-profiles
#
#        - name: Get Flutter packages
#          script: |
#            flutter packages pub get
#
#        - name: Flutter analyze
#          script: |
#            flutter analyze
#
#        - name: Run tests
#          script: |
#            flutter test
#          ignore_failure: false
#
#        - name: Install pods
#          script: |
#            find . -name "Podfile" -execdir pod install \;
#
#        - name: Build IPA
#          script: |
#            BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
#            flutter build ipa --release --build-number=$BUILD_NUMBER
#
#      artifacts:
#        - build/ios/ipa/*.ipa
#
#      publishing:
#        email:
#          recipients:
#            - vlad.razyvika@outlook.fr
#          notify:
#            success: true
#            failure: true
#
#        app_store_connect:
#          auth: integration
#          submit_to_testflight: true
#          beta_groups:
#            - Internal Testers
#          submit_to_app_store: false

  #      app_store_connect:
  #        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
  #        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
  #        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
  #        submit_to_testflight: true
  #        submit_to_app_store: false  # Mettre true pour production

  # android prod inc


  #        android-production:
  #          name: Android Production
  #          max_build_duration: 60
  #          instance_type: linux_x2
  #          working_directory: frontend
  #
  #          environment:
  #            flutter: stable
  #            java: 17
  #
  #            groups:
  #              - google_play_credentials
  #
  #            vars:
  #              PACKAGE_NAME: "com.petits.quizz.de.geo"
  #
  #          triggering:
  #            events:
  #              - push
  #              - tag
  #            branch_patterns:
  #              - pattern: 'main'
  #                include: true
  #                source: true
  #            tag_patterns:
  #              - pattern: 'v*'
  #                include: true
  #            cancel_previous_builds: true
  #
  #          scripts:
  #            - name: Set up local properties
  #              script: |
  #                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
  #
  #            - name: Get Flutter packages
  #              script: |
  #                flutter packages pub get
  #
  #            - name: Flutter analyze
  #              script: |
  #                flutter analyze
  #
  #            - name: Run tests
  #              script: |
  #                flutter test
  #              ignore_failure: false
  #
  #            - name: Build APK
  #              script: |
  #                BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
  #                flutter build apk --release --build-number=$BUILD_NUMBER
  #
  #            - name: Build App Bundle
  #              script: |
  #                BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
  #                flutter build appbundle --release --build-number=$BUILD_NUMBER
  #
  #          artifacts:
  #            - build/app/outputs/**/*.apk
  #            - build/app/outputs/**/*.aab
  #
  #          publishing:
  #            email:
  #              recipients:
  #                - votre-email@example.com
  #              notify:
  #                success: true
  #                failure: true
  #
  #            google_play:
  #              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  #              track: internal
  #              submit_as_draft: true