#name: Backend CI
#
#on:
#  push:
#    branches: [main, develop]
#    paths:
#      - 'backend/**'
#      - '.github/workflows/backend-ci.yml'
#  pull_request:
#    branches: [main, develop]
#    paths:
#      - 'backend/**'
#
#env:
#  CARGO_TERM_COLOR: always
#  RUST_BACKTRACE: 1
#  DATABASE_URL_TEST: postgresql://quiz_user:quiz_test@localhost:5432/quiz_db_test
#
#jobs:
#  lint:
#    name: Lint & Format
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install Rust
#        uses: dtolnay/rust-toolchain@stable
#        with:
#          components: rustfmt, clippy
#
#      - name: Cache cargo
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            backend/target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#
#      - name: Check formatting
#        working-directory: backend/quiz_core_service
#        run: cargo fmt -- --check
#
#      - name: Run Clippy
#        working-directory: backend/quiz_core_service
#        run: cargo clippy -- -D warnings
#
#  test:
#    runs-on: ubuntu-latest
#
#    services:
#      postgres:
#        image: postgres:15
#        env:
#          POSTGRES_USER: quiz_user
#          POSTGRES_PASSWORD: quiz_test
#          POSTGRES_DB: quiz_db_test
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
#
#    env:
##      DATABASE_URL: postgresql://quiz_user:quiz_test@localhost:5432/quiz_db_test
#      #Si bdd local la lancé avant de act push
#      DATABASE_URL: >-
#        ${{ env.ACT == 'true' &&
#            'postgresql://quiz_user:quiz_password@host.docker.internal:5432/quiz_db' ||
#            'postgresql://quiz_user:quiz_test@localhost:5432/quiz_db_test' }}
#      # ✅ Variable pour skip en local
#      SKIP_DB_TESTS: ${{ env.ACT || 'false' }}
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: dtolnay/rust-toolchain@stable
#
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            backend/target
#          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
#
#      - name: Install SQLx CLI
#        if: env.ACT != 'true'  # ✅ Skip si act
#        run: cargo install sqlx-cli --no-default-features --features postgres
#
#      - name: Run migrations
#        if: env.ACT != 'true'  # ✅ Skip si act
#        working-directory: backend/quiz_core_service
#        run: sqlx migrate run
#
#      - name: Run tests (without DB)
#        if: env.ACT == 'true'  # ✅ Seulement en local
#        working-directory: backend/quiz_core_service
#        run: cargo test --lib --verbose
#
#      - name: Run tests (with DB)
#        if: env.ACT != 'true'  # ✅ Seulement sur GitHub
#        working-directory: backend/quiz_core_service
#        run: cargo test --verbose
#
#      - name: Run integration tests
#        working-directory: backend/quiz_core_service
#        run: cargo test --test '*' --verbose
#
#  build:
#    name: Build Docker Image
#    runs-on: ubuntu-latest
#    needs: [lint, test]
#    if: github.event_name == 'push'
#
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Extract metadata
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ghcr.io/${{ github.repository }}/quiz-backend
#          tags: |
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
#            type=sha,prefix={{branch}}-
#            type=raw,value=latest,enable={{is_default_branch}}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: ./backend
#          file: ./docker/backend.Dockerfile
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          build-args: |
#            RUST_VERSION=1.75
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: ghcr.io/${{ github.repository }}/quiz-backend:${{ github.sha }}
#          format: 'sarif'
#          output: 'trivy-results.sarif'
#          severity: 'CRITICAL,HIGH'
#
#      - name: Upload Trivy results to GitHub Security
#        uses: github/codeql-action/upload-sarif@v2
#        if: always()
#        with:
#          sarif_file: 'trivy-results.sarif'