name: Hello World

on:
  push:
    branches: [main, develop]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Display date
        run: date

      - name: List files
        run: ls -la